"""Initial migration - Add all task columns

Revision ID: df4481a75256
Revises: 
Create Date: 2025-11-12 23:13:43.874913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4481a75256'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_category', table_name='tasks')
    op.drop_index('idx_due_date', table_name='tasks')
    op.create_index(op.f('ix_tasks_category'), 'tasks', ['category'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_category'), table_name='tasks')
    op.create_index('idx_due_date', 'tasks', ['due_date'], unique=False)
    op.create_index('idx_category', 'tasks', ['category'], unique=False)
    # ### end Alembic commands ###
